### ISSUE TITLE
Deprecation of K&R function defs

### ISSUE THREAD

**Issue by kargaroc** [rhalkyard/macintosh-c-by-example#1]
Not sure how relevant this is, but given this is supposed to be used as an example of a Retro68 project I think its worth mentioning.
K&R function definitions, as used in files like [this](https://github.com/rhalkyard/macintosh-c-by-example/blob/main/06-MiniGenApp/FileUtil.c), will be going away in C23.
I really doubt GCC will *ever* remove support for these, but either these should probably be updated, or C89 explicitly requested in the build flags.

**Comment by rhalkyard** [comment]
Good catch; rather than change all those function definitions, I've taken the build-flag route.
